### PR TITLE
Most specific include rule wins against exclude rule

### PR DESCRIPTION
**Pull request by VladRassokhin**

### CODE REVIEW

**Comment by VladRassokhin** [comment]
Ping ;)

**Comment by jonnyzzz** [comment]
@chashnikov I'm about to merge the pull request, so it makes longer rules win, e.g. for 
```
        1.7 => aaa/bbb.jar
         - => aaa/b
```
we would have ```aaa/bbb.jar!sss``` be matching but before it was not matching
Do you think it may break your usages?

**Comment by jonnyzzz** [comment]
@VladRassokhin could you please include an example of settings you'd like to use once the pull request is merged?

**Comment by chashnikov** [comment]
I don't think it would break our usages.

**Comment by jonnyzzz** [comment]
Overall the example I included above shows the behaviour of pattern matcher is changed by the pull request. This may mean we may see a number of patterns that are interpreted in the other way, thus we may have required to add a number of extra include/exclude rules to *existing* fix patterns. 

I checked usages for TeamCity and Upsource. Both does not have issues with changing of -rules semantics.

**Comment by jonnyzzz** [comment]
The fix is merged. Please let me know if you see any issues with it

**Comment by jonnyzzz** [comment]
@VladRassokhin Thanks for pinging me to resolve it :)

**Pull request merged**
